### PR TITLE
Configure plugin to be used with `phpstan/extension-installer`

### PR DESCRIPTION
**Pull request by maks-rafalko**
Depends on https://github.com/sidz/phpstan-rules/pull/7 and https://github.com/sidz/phpstan-rules/pull/8 (see the last commit only)

- [x] Check if it really works, by requesting this branch on some real project

### CODE REVIEW

**Comment by sidz** [comment]
Thanks @maks-rafalko.

Have you had a chance to test it on real project? 
Could you please rebase your branch against latest master?

**Comment by maks-rafalko** [comment]
> Have you had a chance to test it on real project?

going to do that, will let you know

**Comment by maks-rafalko** [comment]
Checked here https://github.com/maks-rafalko/radom-php-tests/commit/98f8c4f200025e4679186ca9538627c59da196e6, works as expected!

https://github.com/maks-rafalko/radom-php-tests/blob/98f8c4f200025e4679186ca9538627c59da196e6/composer.json#L28

изображение


@sidz ready for re-review

**Review by sidz — APPROVED** [review]

**Comment by sidz** [comment]
Thanks @maks-rafalko

**Pull request merged**
